package:
  name: perses-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm >=6.3
    - numpy
    - scipy
    #- openmoltools
    #- alchemy

  run:
    - python
    - openmm >=6.3
    - numpy
    - scipy
    - numexpr
    - openeye
    #- openmoltools
    #- alchemy

test:
  requires:
    - nose
  imports:
    - perses

about:
  home: https://github.com/choderalab/perses
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
