package:
  name: perses-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - numexpr
    - autograd
    - pymbar-dev
    - openmm-dev
    - parmed-dev
    - openmoltools-dev
    - alchemy-dev
    - openmmtools-dev
    - numba

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - numexpr
    - autograd
    - pymbar-dev
    - openmm-dev
    - parmed-dev
    - openmoltools-dev
    - alchemy-dev
    - openmmtools-dev
    - numba

test:
  requires:
    - nose
  imports:
    - perses


about:
  home: https://github.com/choderalab/perses
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
